package com.lokendra.springecom.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import com.google.genai.Client;

import com.google.genai.types.GenerateContentConfig;
import com.google.genai.types.GenerateContentResponse;
import com.google.genai.types.Part;

@Service
public class AiImageGeneratorService {

    private final Client client;

    public AiImageGeneratorService(
            @Value("${spring.ai.google.genai.api-key}") String apiKey) {

        this.client = Client.builder()
                .apiKey(apiKey)
                .build();
    }

    public String testConnection() {

    return client.models.generateContent(
            "gemini-3.5-flash",
            "Say only one word: Connected.",
            null
    ).text();
    }

    public byte[] generateImage(String imagePrompt) {

    GenerateContentConfig config = GenerateContentConfig.builder()
            .responseModalities("TEXT", "IMAGE")
            .build();

    GenerateContentResponse response = client.models.generateContent(
            "gemini-3.1-flash-image",
            imagePrompt,
            config
    );

    for (Part part : response.parts()) {

        if (part.inlineData().isPresent()) {
            return part.inlineData().get().data().get();
        }

    }

    throw new RuntimeException("No image was generated by Gemini.");
}
}